name: Cypress Tests
on: [push]

jobs:
  main-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run – Main
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: false
          config-file: cypress.config.js
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  shop-tests:
    runs-on: ubuntu-latest
    needs: main-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run – Shop
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: false
          config-file: cypress.shop.config.js
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs-tests:
    runs-on: ubuntu-latest
    needs: shop-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run – Docs
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: false
          config-file: cypress.docs.config.js
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
